// Institutional Seed Data: Offence Categories, Personas, Precedents, and Active Dockets

import { Case, OffenceCategory, PrecedentIndex, UserPersona } from '@/types';

export const USER_PERSONAS: UserPersona[] = [
  {
    id: 'user-hod-cse',
    name: 'Dr. Meera Sharma',
    role: 'HEAD_OF_DEPARTMENT',
    department: 'Computer Science & Engineering',
    designation: 'Professor & Head of Department',
    email: 'm.sharma@institution.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-dean-students',
    name: 'Prof. Arthur Sterling',
    role: 'DEAN_STUDENT_AFFAIRS',
    department: 'Office of Student Affairs',
    designation: 'Dean of Student Affairs',
    email: 'a.sterling@institution.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-committee-chair',
    name: 'Dr. Rajiv Menon',
    role: 'COMMITTEE_MEMBER',
    department: 'Electrical Engineering & Ethics Council',
    designation: 'Committee Chair / Senior Fellow',
    email: 'r.menon@institution.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-registrar',
    name: 'Sarah Jenkins, Esq.',
    role: 'ADMIN_REGISTRAR',
    department: 'Registrar & Legal Compliance',
    designation: 'Chief Compliance Officer & Registrar',
    email: 's.jenkins@institution.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-governance-viewer',
    name: 'Oversight Council Audit',
    role: 'GOVERNANCE_VIEWER',
    department: 'University Senate Oversight',
    designation: 'External Due-Process Auditor',
    email: 'audit.senate@institution.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
];

export const OFFENCE_CATEGORIES: OffenceCategory[] = [
  {
    id: 'cat-acad-01',
    code: 'ACAD-01',
    name: 'Academic Dishonesty & Assessment Irregularity',
    severity: 'MODERATE',
    description: 'Unauthorized collaboration, plagiarism in term papers, or illicit aid during internal examinations.',
    procedureReference: 'Academic Integrity Code, Section 4.2 (Sub-clause B)',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 3,
    sanctionRangeGuide: 'Formal Reprimand, Zero Grade on Assignment, or Remedial Academic Integrity Seminar.',
  },
  {
    id: 'cat-acad-02',
    code: 'ACAD-02',
    name: 'Examination Compromise & Impersonation',
    severity: 'MAJOR',
    description: 'Possession of unauthorized electronic materials, candidate impersonation, or leaking assessment material.',
    procedureReference: 'Examination Disciplinary Code, Section 4.4',
    defaultQuorum: 4,
    responseWindowDays: 5,
    appealWindowDays: 14,
    retentionYears: 5,
    sanctionRangeGuide: 'Course Cancellation, Suspension for 1-2 Semesters, or Ineligibility for Academic Honors.',
  },
  {
    id: 'cat-cond-01',
    code: 'COND-01',
    name: 'Campus Disorder & Class Disruption',
    severity: 'MINOR',
    description: 'Repeated disruption of university proceedings, willful insubordination, or non-hazardous disorderly conduct.',
    procedureReference: 'Student Code of Conduct, Section 2.1',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 2,
    sanctionRangeGuide: 'Admonition, Written Apology, Campus Restitution Service (up to 20 hours).',
  },
  {
    id: 'cat-cond-02',
    code: 'COND-02',
    name: 'Institutional Property Damage & Facility Misuse',
    severity: 'MODERATE',
    description: 'Defacement of academic facilities, laboratory equipment tampering, or unauthorized physical breach.',
    procedureReference: 'Campus Safety & Property Statute, Section 2.5',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 3,
    sanctionRangeGuide: 'Full Restitution Cost Recovery, Restricted Campus Facility Access, Probation.',
  },
  {
    id: 'cat-cond-03',
    code: 'COND-03',
    name: 'Harassment, Intimidation & Safety Violation',
    severity: 'CRITICAL',
    description: 'Verbal, physical, or cyber-intimidation, discriminatory harassment, or actions endangering student safety.',
    procedureReference: 'Anti-Harassment & Safe Campus Charter, Section 5.1',
    defaultQuorum: 5,
    responseWindowDays: 5,
    appealWindowDays: 14,
    retentionYears: 7,
    sanctionRangeGuide: 'No-Contact Directive, Formal Suspension, Mandatory Counseling, or Dismissal from University.',
  },
];

export const PRECEDENT_INDEX: PrecedentIndex[] = [
  {
    id: 'prec-001',
    offenceCategoryId: 'cat-acad-01',
    categoryCode: 'ACAD-01',
    categoryName: 'Academic Dishonesty',
    anonymizedCaseRef: 'PREC-2024-0014',
    generalizedFacts: 'Student submitted software project containing substantial duplicated repository code without citation. Admitted negligence during preliminary hearing.',
    mitigatingFactors: 'First-time offence; full disclosure upon inquiry; complete cooperative demeanor.',
    aggravatingFactors: 'None noted.',
    sanctionImposedRange: 'Grade reduced to F for specific lab component; mandatory 8-hour academic citation workshop.',
    yearResolved: 2024,
    searchKeywords: ['code plagiarism', 'git repository', 'software engineering', 'unauthorized collaboration'],
  },
  {
    id: 'prec-002',
    offenceCategoryId: 'cat-acad-02',
    categoryCode: 'ACAD-02',
    categoryName: 'Examination Compromise',
    anonymizedCaseRef: 'PREC-2023-0089',
    generalizedFacts: 'Student brought concealed mobile communication device into proctored mid-semester examination hall.',
    mitigatingFactors: 'Demonstrated device was not actively transmitting answers.',
    aggravatingFactors: 'Violation of explicit pre-examination notice prohibiting digital devices.',
    sanctionImposedRange: 'Cancellation of examination paper score; placed on one-semester disciplinary probation.',
    yearResolved: 2023,
    searchKeywords: ['cell phone', 'midterm', 'exam hall', 'unauthorized device', 'smartwatch'],
  },
  {
    id: 'prec-003',
    offenceCategoryId: 'cat-cond-02',
    categoryCode: 'COND-02',
    categoryName: 'Property Damage',
    anonymizedCaseRef: 'PREC-2024-0042',
    generalizedFacts: 'Damage sustained by optical microscope stage in undergraduate robotics laboratory during unmonitored evening hours.',
    mitigatingFactors: 'Student reported the mechanical fault next morning and offered full compensation.',
    aggravatingFactors: 'Operating equipment outside authorized lab operating schedule.',
    sanctionImposedRange: 'Financial restitution ($450) + mandatory laboratory safety re-certification.',
    yearResolved: 2024,
    searchKeywords: ['lab equipment', 'microscope', 'damage', 'unsupervised access', 'restitution'],
  },
  {
    id: 'prec-004',
    offenceCategoryId: 'cat-cond-03',
    categoryCode: 'COND-03',
    categoryName: 'Harassment & Safety',
    anonymizedCaseRef: 'PREC-2025-0003',
    generalizedFacts: 'Repeated offensive digital communications sent to peer group forum post-midnight creating intimidating climate.',
    mitigatingFactors: 'Participated in voluntary mediation session.',
    aggravatingFactors: 'Continued messages following verbal request from class coordinator to cease.',
    sanctionImposedRange: 'Campus housing reassignment; formal no-contact order for academic year; 10 hours counseling.',
    yearResolved: 2025,
    searchKeywords: ['harassment', 'social media', 'online intimidation', 'no-contact order', 'dormitory'],
  },
];

export const INITIAL_CASES: Case[] = [
  {
    id: 'case-2026-00042',
    caseNumber: 'DISC-2026-00042',
    title: 'Unauthorized Collaboration on Advanced Algorithms Benchmark Lab',
    status: 'RESPONSE_WINDOW',
    department: 'Computer Science & Engineering',
    studentRegNoHash: '7c9e2b8a4f1a23847b2c91823746a5b6c7d8e9f0',
    studentDisplayRef: 'Student Ref #CS-8902',
    competentAuthorityId: 'user-hod-cse',
    offenceCategoryId: 'cat-acad-01',
    offenceCategory: OFFENCE_CATEGORIES[0],
    createdAt: '2026-09-08T10:30:00Z',
    updatedAt: '2026-09-10T14:15:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00042',
      caseId: 'case-2026-00042',
      incidentDate: '2026-09-06T14:00:00Z',
      location: 'Turing Computer Lab 3B',
      description: 'During automated AST similarity grading for Algorithms Lab 4, an anomalous 94% code structure overlap was flagged between two benchmark submissions.',
      reportingPerson: 'Dr. Meera Sharma (HoD - CSE)',
      reportingDepartment: 'Computer Science & Engineering',
      witnessCount: 2,
      createdAt: '2026-09-08T10:30:00Z',
      evidenceItems: [
        {
          id: 'ev-01',
          fileName: 'similarity_report_ast_diff.pdf',
          fileSize: 428000,
          mimeType: 'application/pdf',
          sha256Checksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          storageKey: 'cases/2026-00042/evidence/ast_diff.pdf',
          uploadedBy: 'Dr. Meera Sharma',
          uploadedAt: '2026-09-08T10:35:00Z',
        },
        {
          id: 'ev-02',
          fileName: 'git_commit_timings_log.csv',
          fileSize: 18400,
          mimeType: 'text/csv',
          sha256Checksum: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
          storageKey: 'cases/2026-00042/evidence/git_timings.csv',
          uploadedBy: 'Dr. Meera Sharma',
          uploadedAt: '2026-09-08T10:36:00Z',
        },
      ],
    },
    checklistItems: [
      {
        id: 'chk-1',
        caseId: 'case-2026-00042',
        stepNumber: 1,
        requirement: 'Incident Evidence Verification & Hash Registry',
        description: 'Verify AST diff and repository logs; calculate SHA-256 digests.',
        dueDate: '2026-09-09T18:00:00Z',
        completedAt: '2026-09-08T11:00:00Z',
        completedBy: 'System Auto-Audit',
        status: 'COMPLETED',
        notes: 'Hashes locked into WORM tamper-evident storage.',
      },
      {
        id: 'chk-2',
        caseId: 'case-2026-00042',
        stepNumber: 2,
        requirement: 'Issue Prescribed Notice of Charge',
        description: 'Dispatch formal Notice of Charge citing Academic Integrity Code Sec 4.2.',
        dueDate: '2026-09-10T18:00:00Z',
        completedAt: '2026-09-10T09:30:00Z',
        completedBy: 'Sarah Jenkins, Esq. (Admin)',
        status: 'COMPLETED',
        evidenceRef: 'not-001',
      },
      {
        id: 'chk-3',
        caseId: 'case-2026-00042',
        stepNumber: 3,
        requirement: 'Statutory Response Window (7 Days)',
        description: 'Awaiting student written explanation or admission of facts.',
        dueDate: '2026-09-17T18:00:00Z',
        status: 'IN_PROGRESS',
        notes: 'Notice delivered via recorded email delivery on 10-Sep-2026. 5 days remaining.',
      },
      {
        id: 'chk-4',
        caseId: 'case-2026-00042',
        stepNumber: 4,
        requirement: 'Constitute Disciplinary Committee (Quorum: 3)',
        description: 'Appoint quorum of 3 disciplinary panel members.',
        dueDate: '2026-09-20T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-5',
        caseId: 'case-2026-00042',
        stepNumber: 5,
        requirement: 'Issue Hearing Summons with 72-Hour Notice',
        description: 'Designate hearing chamber and notice of representation.',
        dueDate: '2026-09-23T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-6',
        caseId: 'case-2026-00042',
        stepNumber: 6,
        requirement: 'Human Deliberation & Reasoned Order Entry',
        description: 'Record human verdict and sanction. AI output strictly forbidden.',
        dueDate: '2026-09-26T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-7',
        caseId: 'case-2026-00042',
        stepNumber: 7,
        requirement: 'Statutory Appeal Window (14 Days)',
        description: 'Allow window for appeal to Executive Board.',
        dueDate: '2026-10-10T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-8',
        caseId: 'case-2026-00042',
        stepNumber: 8,
        requirement: 'Sanction Compliance & Retention Timer',
        description: 'Track academic integrity seminar and set 3-year purge clock.',
        dueDate: '2026-10-30T18:00:00Z',
        status: 'PENDING',
      },
    ],
    notices: [
      {
        id: 'not-001',
        caseId: 'case-2026-00042',
        caseNumber: 'DISC-2026-00042',
        type: 'NOTICE_OF_CHARGE',
        recipientRef: 'official.student.cs8902@institution.edu',
        subject: 'FORMAL NOTICE OF DISCIPLINARY CHARGE — Ref: DISC-2026-00042',
        contentMarkdown: `### OFFICE OF THE REGISTRAR & DISCIPLINARY TRIBUNAL
**DATE:** 10 September 2026  
**CASE FILE:** DISC-2026-00042  
**RESPONDENT:** Student Record Reference #CS-8902  

**STATEMENT OF ALLEGATION:**
You are formally notified of an inquiry under Academic Integrity Code Section 4.2 regarding anomalous code duplication in Assignment 4 (Algorithms).

**STATUTORY RIGHTS & PROCEDURES:**
1. You have the right to submit a written reply within **7 calendar days** (Deadline: 17 September 2026, 18:00).
2. You have the right to be accompanied by a student advocate during any oral hearing.
3. You are presumed innocent of intentional misconduct until the competent authority concludes deliberation.`,
        generatedDocHash: '3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855a',
        deliveryStatus: 'DELIVERED',
        deliveryProof: 'SES-REC-20260910-9948271 (Server Delivered & Opened)',
        responseDeadline: '2026-09-17T18:00:00Z',
        sentAt: '2026-09-10T09:30:00Z',
        createdAt: '2026-09-10T09:15:00Z',
      },
    ],
    committeeRecord: {
      id: 'com-00042',
      caseId: 'case-2026-00042',
      committeeChair: 'Dr. Rajiv Menon',
      membersAssigned: ['Dr. Rajiv Menon', 'Prof. Arthur Sterling', 'Dr. Elena Rostova'],
      quorumRequired: 3,
      quorumPresent: 3,
      isQuorumMet: true,
      studentAttended: false,
      updatedAt: '2026-09-10T14:15:00Z',
    },
  },
  {
    id: 'case-2026-00038',
    caseNumber: 'DISC-2026-00038',
    title: 'Disorderly Conduct & Sound System Breach in Central Quadrangle',
    status: 'DECISION_RECORDED',
    department: 'Office of Student Affairs',
    studentRegNoHash: '4a1b2c3d4e5f67890123456789abcdef01234567',
    studentDisplayRef: 'Student Ref #ME-4410',
    competentAuthorityId: 'user-dean-students',
    offenceCategoryId: 'cat-cond-01',
    offenceCategory: OFFENCE_CATEGORIES[2],
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-02T16:00:00Z',
    isPurged: false,
    checklistItems: [],
    notices: [],
    committeeRecord: {
      id: 'com-00038',
      caseId: 'case-2026-00038',
      committeeChair: 'Prof. Arthur Sterling',
      membersAssigned: ['Prof. Arthur Sterling', 'Dr. Meera Sharma', 'Dr. David Vance'],
      hearingDate: '2026-09-01T14:00:00Z',
      hearingVenue: 'Senate Chamber B',
      quorumRequired: 3,
      quorumPresent: 3,
      isQuorumMet: true,
      studentAttended: true,
      studentRepresentative: 'Student Council Ombudsman',
      deliberationMinutes: 'Student demonstrated remorse and explained amplification was unauthorized addition by third party. Quorum confirmed unanimous finding of minor responsibility.',
      updatedAt: '2026-09-01T16:30:00Z',
    },
    decision: {
      id: 'dec-00038',
      caseId: 'case-2026-00038',
      decidedBy: 'Prof. Arthur Sterling (Dean of Student Affairs)',
      decidingAuthority: 'Office of the Dean of Student Affairs',
      verdict: 'Charge Substantiated (Minor Infraction)',
      reasoningText: 'Having evaluated the testimony and witness logs, the committee determined that while sound decibel limits were exceeded, the student took prompt corrective action when requested by campus security. A proportional educational remedy is appropriate.',
      sanctionImposed: 'Written Admonition + 10 Hours Campus Library Service restitution',
      sanctionStartDate: '2026-09-05T00:00:00Z',
      sanctionEndDate: '2026-09-30T00:00:00Z',
      appealRoute: 'Executive Disciplinary Appeals Tribunal',
      appealDeadline: '2026-09-16T18:00:00Z',
      appealSubmitted: false,
      decidedAt: '2026-09-02T15:30:00Z',
      decisionDocHash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    },
  },
];
