// Institutional Seed Data: Offence Categories, Personas, Precedents, and Active Dockets
// Formatted for EDUguard — Student Discipline Agent

import { Case, OffenceCategory, PrecedentIndex, UserPersona } from '@/types';

export const USER_PERSONAS: UserPersona[] = [
  {
    id: 'user-hod-cse',
    name: 'Dr. Meera Sharma',
    role: 'HEAD_OF_DEPARTMENT',
    department: 'Computer Science & Engineering',
    designation: 'Professor & Head of Department',
    email: 'm.sharma@institution.edu',
    employeeId: 'EMP-1001',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-dean-students',
    name: 'Prof. Arthur Sterling',
    role: 'DEAN_STUDENT_AFFAIRS',
    department: 'Office of Student Affairs',
    designation: 'Dean of Student Affairs',
    email: 'a.sterling@institution.edu',
    employeeId: 'EMP-1004',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-committee-chair',
    name: 'Dr. Rajiv Menon',
    role: 'COMMITTEE_MEMBER',
    department: 'Electrical Engineering & Ethics Council',
    designation: 'Committee Chair / Senior Fellow',
    email: 'r.menon@institution.edu',
    employeeId: 'EMP-1002',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-registrar',
    name: 'Sarah Jenkins, Esq.',
    role: 'ADMIN_REGISTRAR',
    department: 'Registrar & Legal Compliance',
    designation: 'Chief Compliance Officer & Registrar',
    email: 's.jenkins@institution.edu',
    employeeId: 'EMP-1003',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-governance-viewer',
    name: 'Oversight Council Audit',
    role: 'GOVERNANCE_VIEWER',
    department: 'University Senate Oversight',
    designation: 'External Due-Process Auditor',
    email: 'audit.senate@institution.edu',
    employeeId: 'EMP-9000',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-student-portal',
    name: 'Rahul Verma',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    designation: 'Undergraduate Student (B.Tech CSE)',
    email: 'rahul.verma@student.institution.edu',
    studentRollNo: 'CS-8902',
    studentBatch: '2024 - 2028',
    activeCaseId: 'EDU-2026-00042',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-student-general',
    name: 'Ananya Sharma',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    designation: 'Undergraduate Student (B.Tech CSE)',
    email: 'ananya.sharma@student.institution.edu',
    studentRollNo: 'CS-9104',
    studentBatch: '2024 - 2028',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
];


// 5-Point Policy & Offence Mapping (Step 2 of EDUguard workflow)
export const OFFENCE_CATEGORIES: OffenceCategory[] = [
  {
    id: 'cat-acad-01',
    code: 'ACAD-01',
    name: 'Academic Dishonesty & Assessment Irregularity',
    applicablePolicy: 'Institutional Code of Academic Integrity & Student Ethics (2026 Edition)',
    relevantClause: 'Section 4.2, Clause B: Unauthorized Collaboration & Uncited Source Duplication',
    requiredProcedure: 'Issuance of formal Show-Cause Notice, statutory 7-day response window, 3-member inquiry panel hearing',
    competentAuthority: 'Head of Department (HoD) in concurrence with Faculty Ethics Committee',
    severity: 'MODERATE',
    description: 'Unauthorized collaboration, plagiarism in term assignments, code cloning without citation, or illicit aid during internal assessments.',
    procedureReference: 'Academic Integrity Code, Section 4.2 (Sub-clause B)',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 3,
    sanctionRangeGuide: 'Formal Reprimand, Assignment Grade Nullification, Remedial Academic Integrity Seminar, or Restitution Assignment.',
  },
  {
    id: 'cat-acad-02',
    code: 'ACAD-02',
    name: 'Examination Compromise & Impersonation',
    applicablePolicy: 'Central Examination Conduct & Proctorial Regulations (Statute XII)',
    relevantClause: 'Section 4.4, Sub-clause A: Possession of Prohibited Electronic Devices & Unauthorized Communication',
    requiredProcedure: 'Immediate proctorial confiscation, 5-day response window, 4-member Standing Disciplinary Board hearing',
    competentAuthority: 'Dean of Academic Affairs & Proctorial Board of Inquest',
    severity: 'MAJOR',
    description: 'Possession of unauthorized electronic communication equipment, candidate impersonation, or unauthorized access to examination materials.',
    procedureReference: 'Examination Disciplinary Code, Section 4.4',
    defaultQuorum: 4,
    responseWindowDays: 5,
    appealWindowDays: 14,
    retentionYears: 5,
    sanctionRangeGuide: 'Course Cancellation, Suspension for 1-2 Semesters, or Ineligibility for Academic Honors and Placements.',
  },
  {
    id: 'cat-cond-01',
    code: 'COND-01',
    name: 'Campus Disorder & Class Disruption',
    applicablePolicy: 'University Student Code of Conduct & Community Standards',
    relevantClause: 'Section 2.1, Clause C: Obstruction of Academic Proceedings & Noise Violations',
    requiredProcedure: 'Incident report filing, 7-day explanation window, summary departmental inquiry',
    competentAuthority: 'Dean of Student Affairs / Campus Proctorial Council',
    severity: 'MINOR',
    description: 'Repeated disruption of university instructional proceedings, willful insubordination to marshals, or non-hazardous disorderly conduct.',
    procedureReference: 'Student Code of Conduct, Section 2.1',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 2,
    sanctionRangeGuide: 'Admonition, Written Apology, Campus Restitution Service (up to 20 hours).',
  },
  {
    id: 'cat-cond-02',
    code: 'COND-02',
    name: 'Institutional Property Damage & Facility Misuse',
    applicablePolicy: 'Campus Safety, Property Maintenance & Facility Security Statute',
    relevantClause: 'Section 2.5, Clause A: Laboratory Apparatus Tampering & Unauthorized Equipment Operation',
    requiredProcedure: 'Security asset damage assessment, 7-day notice, joint technical hearing',
    competentAuthority: 'Director of Campus Infrastructure & Dean of Student Affairs',
    severity: 'MODERATE',
    description: 'Defacement of academic facilities, unauthorized laboratory equipment tampering, or unauthorized physical breach.',
    procedureReference: 'Campus Safety & Property Statute, Section 2.5',
    defaultQuorum: 3,
    responseWindowDays: 7,
    appealWindowDays: 14,
    retentionYears: 3,
    sanctionRangeGuide: 'Full Financial Restitution Cost Recovery, Restricted Campus Facility Access, Probation.',
  },
  {
    id: 'cat-cond-03',
    code: 'COND-03',
    name: 'Harassment, Intimidation & Safety Violation',
    applicablePolicy: 'Zero-Tolerance Anti-Harassment & Safe Campus Governance Charter',
    relevantClause: 'Section 5.1, Clause B: Hostile Environment Creation & Targeted Cyber-Intimidation',
    requiredProcedure: 'Immediate interim protective directives, 5-day response, 5-member High-Level Disciplinary Committee hearing',
    competentAuthority: 'Executive Disciplinary Tribunal & Dean of Student Affairs',
    severity: 'CRITICAL',
    description: 'Verbal, physical, or cyber-intimidation, discriminatory harassment, or deliberate actions endangering member safety.',
    procedureReference: 'Anti-Harassment & Safe Campus Charter, Section 5.1',
    defaultQuorum: 5,
    responseWindowDays: 5,
    appealWindowDays: 14,
    retentionYears: 7,
    sanctionRangeGuide: 'Formal No-Contact Directive, Suspension from Residence, Mandatory Counseling, or Dismissal from University.',
  },
];

export const PRECEDENT_INDEX: PrecedentIndex[] = [
  {
    id: 'prec-001',
    offenceCategoryId: 'cat-acad-01',
    categoryCode: 'ACAD-01',
    categoryName: 'Academic Dishonesty & Assessment Irregularity',
    anonymizedCaseRef: 'PREC-2024-0014',
    title: 'Anomalous Code Duplication in Advanced Algorithms Lab Submission',
    generalizedFacts: 'Student submitted algorithms software project containing substantial duplicated repository code without citation. Admitted negligence during preliminary departmental inquiry.',
    mitigatingFactors: 'First-time offence; full disclosure upon inquiry; complete cooperative demeanor; volunteered to complete remedial ethics modules.',
    aggravatingFactors: 'None noted.',
    sanctionImposedRange: 'Grade reduced to F for specific lab component; mandatory 8-hour academic citation workshop.',
    yearResolved: 2024,
    searchKeywords: ['code plagiarism', 'git repository', 'software engineering', 'unauthorized collaboration', 'ast diff', 'algorithms'],
    offenceType: 'Code Plagiarism & AST Structure Duplication',
    intent: 'NEGLIGENT',
    intentDescription: 'Student shared code during informal peer study session; neglected to implement independent solutions or cite joint brainstorming.',
    circumstances: 'High-stress midterm deadline; lab assignment guidelines permitted verbal discussion but prohibited code sharing.',
    severity: 'MODERATE',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['AST Code Syntax Diff >90%', 'Git Commit Timestamps within 5 minutes', 'TA Witness Statement'],
    caseAttributes: {
      cooperationLevel: 'FULL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Single laboratory milestone (10% of final grade)',
    },
    procedureFollowed: {
      hearingBody: 'Departmental Academic Ethics Panel',
      quorum: 3,
      durationDays: 14,
      representationProvided: true,
      noticesIssued: ['Show-Cause Notice', 'Hearing Summons', 'Reasoned Determination Order'],
      hearingsCount: 1,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Negligent Unauthorized Collaboration',
      sanction: 'Grade of F for Lab Component #4; completion of 8-Hour Academic Citation Seminar',
      reasoningSummary: 'Panel found genuine absence of premeditated deception, but non-delegable breach of academic integrity guidelines warranting educational remediation.',
      appealOutcome: 'No appeal lodged; sanction fully satisfied within 30 days',
      retentionPeriodYears: 3,
    },
  },
  {
    id: 'prec-002',
    offenceCategoryId: 'cat-acad-01',
    categoryCode: 'ACAD-01',
    categoryName: 'Academic Dishonesty & Assessment Irregularity',
    anonymizedCaseRef: 'PREC-2025-0022',
    title: 'Parallel Branch Forking & Cosmetic Variable Renaming in Core Project',
    generalizedFacts: 'Two student repositories displayed identical class architecture and algorithmic control-flow with only variable and comment renames.',
    mitigatingFactors: 'Demonstrated prior satisfactory academic standing; first recorded citation.',
    aggravatingFactors: 'Attempted cosmetic alterations indicated awareness of similarity detection systems.',
    sanctionImposedRange: 'Zero marks on term project; formal written reprimand placed in student dossier.',
    yearResolved: 2025,
    searchKeywords: ['git fork', 'variable renaming', 'obfuscation', 'unauthorized collaboration', 'data structures'],
    offenceType: 'Code Obfuscation & Source Duplication',
    intent: 'RECKLESS',
    intentDescription: 'Deliberate cosmetic variable alterations made to camouflage shared code structure prior to automated submission.',
    circumstances: 'End-of-term capstone milestone; students cited extreme workload and misinterpretation of group collaboration rules.',
    severity: 'MODERATE',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['AST Similarity 96%', 'Git History Squash/Rebase Log', 'Proctor Inquest Interview'],
    caseAttributes: {
      cooperationLevel: 'PARTIAL',
      restitutionOffered: false,
      remorseDemonstrated: true,
      academicImpact: 'Major course project (30% of total grade)',
    },
    procedureFollowed: {
      hearingBody: 'Faculty Disciplinary Committee',
      quorum: 4,
      durationDays: 18,
      representationProvided: true,
      noticesIssued: ['Formal Notice of Charge', 'Evidence Inspection Summons', 'Decision Notice'],
      hearingsCount: 2,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Reckless Code Duplication with Cosmetic Obfuscation',
      sanction: 'Zero score for Term Project; Written Reprimand on Official Record for 1 Year',
      reasoningSummary: 'The presence of systematic variable renaming ruled out accidental duplication, necessitating a proportional grade penalty and formal warning.',
      appealOutcome: 'Appealed to Dean; penalty upheld as consistent with institutional precedent',
      retentionPeriodYears: 3,
    },
  },
  {
    id: 'prec-003',
    offenceCategoryId: 'cat-acad-01',
    categoryCode: 'ACAD-01',
    categoryName: 'Academic Dishonesty & Assessment Irregularity',
    anonymizedCaseRef: 'PREC-2023-0077',
    title: 'Recurrent Plagiarism & Commercial Contract Cheating Submission',
    generalizedFacts: 'Student commissioned third-party freelance developer to construct full compiler implementation and submitted as original work.',
    mitigatingFactors: 'None substantiated.',
    aggravatingFactors: 'Repeat disciplinary referral; active fabrication of commit authorship metadata; financial transaction involved.',
    sanctionImposedRange: 'Failing grade (F) in entire course; suspension from academic programs for 1 semester.',
    yearResolved: 2023,
    searchKeywords: ['contract cheating', 'commercial developer', 'repeat offence', 'compiler', 'plagiarism'],
    offenceType: 'Commercial Contract Cheating & Authorship Fraud',
    intent: 'PREMEDITATED',
    intentDescription: 'Pre-planned engagement with commercial software marketplace to bypass academic evaluation entirely.',
    circumstances: 'Student had received a formal warning in the preceding academic year for minor uncited code borrowing.',
    severity: 'MAJOR',
    occurrenceHistory: 'REPEAT_OFFENCE',
    evidencePatterns: ['Payment Invoices & Chat Records', 'IP Geolocation Anomalies', 'Expert Faculty Oral Code Defense'],
    caseAttributes: {
      cooperationLevel: 'OBSTRUCTIVE',
      restitutionOffered: false,
      remorseDemonstrated: false,
      academicImpact: 'Core required course (100% course cancellation)',
    },
    procedureFollowed: {
      hearingBody: 'Standing University Disciplinary Tribunal',
      quorum: 5,
      durationDays: 32,
      representationProvided: true,
      noticesIssued: ['Show-Cause Notice', 'Interim Suspension Notice', 'Tribunal Hearing Summons', 'Expulsion Review Order'],
      hearingsCount: 3,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Premeditated Commercial Fraud (Repeat Offence)',
      sanction: 'Course Grade F; One-Semester Academic Suspension; Disciplinary Notation',
      reasoningSummary: 'Repeat breach combined with commercial fraud severely compromised institutional accreditation, requiring formal suspension.',
      appealOutcome: 'Appeal dismissed by Executive Appeals Council',
      retentionPeriodYears: 5,
    },
  },
  {
    id: 'prec-004',
    offenceCategoryId: 'cat-acad-02',
    categoryCode: 'ACAD-02',
    categoryName: 'Examination Compromise & Impersonation',
    anonymizedCaseRef: 'PREC-2023-0089',
    title: 'Concealed Smartwatch Device in Proctored Midterm Examination',
    generalizedFacts: 'Student brought concealed smart communication wearable into proctored mid-semester examination hall against clear regulations.',
    mitigatingFactors: 'Demonstrated that device was on airplane mode and had not actively received or transmitted exam solutions.',
    aggravatingFactors: 'Violation of explicit pre-examination notice prohibiting all electronic wearables.',
    sanctionImposedRange: 'Cancellation of examination paper score; placed on one-semester disciplinary probation.',
    yearResolved: 2023,
    searchKeywords: ['cell phone', 'midterm', 'exam hall', 'unauthorized device', 'smartwatch'],
    offenceType: 'Unauthorized Electronic Device in Exam Hall',
    intent: 'RECKLESS',
    intentDescription: 'Student neglected to deposit wearable in designated locker despite marshal warnings; claimed oversight rather than intent to cheat.',
    circumstances: 'Proctored 200-student examination hall; device confiscated upon vibrating during question distribution.',
    severity: 'MAJOR',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['Proctor Confiscation Form', 'Digital Device Device Log', 'Invigilator Incident Log'],
    caseAttributes: {
      cooperationLevel: 'FULL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Mid-semester examination (25% weight)',
    },
    procedureFollowed: {
      hearingBody: 'Central Examination Disciplinary Board',
      quorum: 4,
      durationDays: 10,
      representationProvided: true,
      noticesIssued: ['Examination Violation Notice', 'Hearing Summons', 'Determination Notice'],
      hearingsCount: 1,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Possession of Prohibited Device in Examination Venue',
      sanction: 'Midterm Examination Score Cancelled (0 Marks); 1-Semester Disciplinary Probation',
      reasoningSummary: 'Possession alone constitutes strict liability under Statute XII; lack of transmission mitigated against full course cancellation.',
      appealOutcome: 'No appeal filed',
      retentionPeriodYears: 5,
    },
  },
  {
    id: 'prec-005',
    offenceCategoryId: 'cat-cond-01',
    categoryCode: 'COND-01',
    categoryName: 'Campus Disorder & Class Disruption',
    anonymizedCaseRef: 'PREC-2024-0088',
    title: 'High-Decibel Sound Amplification during Institutional Quiet Hours',
    generalizedFacts: 'High-volume sound amplification operated in hostel quadrangle past midnight during pre-examination study week.',
    mitigatingFactors: 'Immediate voluntary compliance upon security arrival; written apology submitted within 24 hours.',
    aggravatingFactors: 'Activity occurred during designated quiet hours immediately preceding university finals.',
    sanctionImposedRange: 'Formal Written Admonition; 12 hours campus community restoration service.',
    yearResolved: 2024,
    searchKeywords: ['sound amplification', 'quiet hours', 'hostel', 'noise violation', 'community service'],
    offenceType: 'Institutional Quiet Hours Breach & Noise Disturbance',
    intent: 'RECKLESS',
    intentDescription: 'Organizers failed to secure advance permits or monitor acoustic decibel output during quiet hours.',
    circumstances: 'End-of-term student celebration; multiple dormitory resident complaints logged.',
    severity: 'MINOR',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['Security Marshal Incident Log', 'Sound Decibel Peak Telemetry', 'Signed Student Statement'],
    caseAttributes: {
      cooperationLevel: 'FULL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Non-academic conduct matter',
    },
    procedureFollowed: {
      hearingBody: 'Hostel Disciplinary Warden Council',
      quorum: 3,
      durationDays: 7,
      representationProvided: true,
      noticesIssued: ['Explanation Summons', 'Proctorial Decision Notice'],
      hearingsCount: 1,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Violation of Community Standards (Noise Regulation)',
      sanction: 'Formal Written Admonition + 12 Hours Campus Library Maintenance Service',
      reasoningSummary: 'Educational restorative remedy deemed suitable given immediate compliance and prompt written accountability.',
      appealOutcome: 'Complied without appeal',
      retentionPeriodYears: 2,
    },
  },
  {
    id: 'prec-006',
    offenceCategoryId: 'cat-cond-02',
    categoryCode: 'COND-02',
    categoryName: 'Institutional Property Damage & Facility Misuse',
    anonymizedCaseRef: 'PREC-2024-0042',
    title: 'Precision Optical Microscope Stage Damage in Robotics Facility',
    generalizedFacts: 'Damage sustained by optical microscope stage in robotics research facility during unmonitored evening hours.',
    mitigatingFactors: 'Student reported the mechanical fault immediately next morning and offered full financial compensation.',
    aggravatingFactors: 'Operating specialized lab equipment outside designated supervisory hours without authorization.',
    sanctionImposedRange: 'Financial restitution ($450) + mandatory laboratory safety re-certification.',
    yearResolved: 2024,
    searchKeywords: ['lab equipment', 'microscope', 'damage', 'unsupervised access', 'restitution'],
    offenceType: 'Laboratory Apparatus Tampering & Safety Misuse',
    intent: 'ACCIDENTAL',
    intentDescription: 'Equipment damaged due to improper objective lens clearance calibration during unsupervised experimentation.',
    circumstances: 'Student was working on independent capstone prototype after normal laboratory operating hours.',
    severity: 'MODERATE',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['Security Access Keycard Log', 'Technical Assessment Damage Report', 'Self-Reported Email'],
    caseAttributes: {
      cooperationLevel: 'FULL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Lab equipment temporarily offline for 48 hours',
    },
    procedureFollowed: {
      hearingBody: 'Infrastructure & Safety Inquiry Committee',
      quorum: 3,
      durationDays: 12,
      representationProvided: true,
      noticesIssued: ['Damage Assessment Notice', 'Safety Hearing Notice', 'Restitution Order'],
      hearingsCount: 1,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Unauthorized Equipment Operation with Accidental Damage',
      sanction: 'Full Financial Restitution ($450 replacement part cost) + Mandatory 4-Hour Lab Safety Re-certification',
      reasoningSummary: 'Immediate self-reporting and voluntary restitution demonstrated good faith, warranting pure cost recovery and safety re-training.',
      appealOutcome: 'Restitution paid in full; certified complete',
      retentionPeriodYears: 3,
    },
  },
  {
    id: 'prec-007',
    offenceCategoryId: 'cat-cond-03',
    categoryCode: 'COND-03',
    categoryName: 'Harassment, Intimidation & Safety Violation',
    anonymizedCaseRef: 'PREC-2025-0003',
    title: 'Targeted Digital Intimidation in Student Course Communication Channel',
    generalizedFacts: 'Repeated offensive digital messages sent to peer cohort group creating an intimidating environment.',
    mitigatingFactors: 'Participated in voluntary restorative mediation session; no physical confrontation.',
    aggravatingFactors: 'Continued messages following verbal request from class coordinator to cease.',
    sanctionImposedRange: 'Campus housing reassignment; formal no-contact order for academic year; 10 hours counseling.',
    yearResolved: 2025,
    searchKeywords: ['harassment', 'social media', 'online intimidation', 'no-contact order', 'dormitory'],
    offenceType: 'Peer Harassment & Digital Intimidation',
    intent: 'RECKLESS',
    intentDescription: 'Student sent derogatory communications during heated project disagreement without considering coercive impact on peer.',
    circumstances: 'Occurred across external messaging group affiliated with department course cohort.',
    severity: 'CRITICAL',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['Cryptographically Timestamped Chat Logs', 'Witness Peer Statements', 'Coordinator Warning Memo'],
    caseAttributes: {
      cooperationLevel: 'PARTIAL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Disruption of cohort collaborative environment',
    },
    procedureFollowed: {
      hearingBody: 'Executive Disciplinary Tribunal & Dean of Student Affairs',
      quorum: 5,
      durationDays: 21,
      representationProvided: true,
      noticesIssued: ['Interim Protective Directive', 'Notice of Charge', 'Formal Hearing Notice', 'Disciplinary Order'],
      hearingsCount: 2,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Violation of Safe Campus Charter (Digital Intimidation)',
      sanction: 'Formal Academic Year No-Contact Directive; Campus Residence Reassignment; 10 Hours Counseling',
      reasoningSummary: 'Protection of vulnerable community members required immediate separation of parties and ongoing counseling oversight.',
      appealOutcome: 'Upheld by Senate Appeals Tribunal without modification',
      retentionPeriodYears: 7,
    },
  },
  {
    id: 'prec-008',
    offenceCategoryId: 'cat-acad-01',
    categoryCode: 'ACAD-01',
    categoryName: 'Academic Dishonesty & Assessment Irregularity',
    anonymizedCaseRef: 'PREC-2024-0056',
    title: 'Falsified Empirical Data Points in Senior Capstone Experimental Log',
    generalizedFacts: 'Senior undergraduate researcher fabricated control-group thermal performance readings in capstone engineering thesis.',
    mitigatingFactors: 'Admitted fabrication when questioned during technical audit; no external publication had occurred.',
    aggravatingFactors: 'Research was funded by institutional innovation grant; scientific integrity compromised.',
    sanctionImposedRange: 'Thesis rejection; required to repeat research semester under new supervisor; ethics tutorial.',
    yearResolved: 2024,
    searchKeywords: ['data fabrication', 'capstone thesis', 'falsified readings', 'engineering', 'research ethics'],
    offenceType: 'Research Data Fabrication & Empirical Falsification',
    intent: 'PREMEDITATED',
    intentDescription: 'Generated synthetic sensor values in spreadsheet when laboratory thermal chamber experienced scheduled downtime.',
    circumstances: 'Upcoming graduation deadline and pressure to demonstrate statistically significant outcomes.',
    severity: 'MAJOR',
    occurrenceHistory: 'FIRST_TIME',
    evidencePatterns: ['Raw Laboratory Sensor Log Timestamps', 'Discrepancy Audit Report', 'Faculty Inquest Transcript'],
    caseAttributes: {
      cooperationLevel: 'FULL',
      restitutionOffered: true,
      remorseDemonstrated: true,
      academicImpact: 'Senior capstone thesis requirement',
    },
    procedureFollowed: {
      hearingBody: 'Research Integrity & Academic Ethics Board',
      quorum: 4,
      durationDays: 25,
      representationProvided: true,
      noticesIssued: ['Notice of Data Irregularity', 'Ethics Board Summons', 'Determination Order'],
      hearingsCount: 2,
    },
    outcomeRecorded: {
      finding: 'Substantiated — Scientific Misconduct (Empirical Data Fabrication)',
      sanction: 'Capstone Thesis Submission Invalidated; 1-Semester Extension Required with New Proctored Research Protocol',
      reasoningSummary: 'Falsification of empirical findings directly strikes at institutional academic credibility, requiring nullification of the submitted research work.',
      appealOutcome: 'Accepted findings; completed extension successfully',
      retentionPeriodYears: 5,
    },
  },
];

export const INITIAL_CASES: Case[] = [
  {
    id: 'case-2026-00042',
    caseNumber: 'EDU-2026-00042',
    title: 'Unauthorized Collaboration on Advanced Algorithms Benchmark Lab',
    status: 'RESPONSE_WINDOW',
    department: 'Computer Science & Engineering',
    studentRegNoHash: '7c9e2b8a4f1a23847b2c91823746a5b6c7d8e9f0',
    studentDisplayRef: 'Student Ref #CS-8902',
    competentAuthorityId: 'user-hod-cse',
    offenceCategoryId: 'cat-acad-01',
    offenceCategory: OFFENCE_CATEGORIES[0],
    createdAt: '2026-09-08T10:30:00Z',
    updatedAt: '2026-09-10T14:15:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00042',
      caseId: 'case-2026-00042',
      incidentDate: '2026-09-06T14:00:00Z',
      location: 'Turing Computer Lab 3B',
      description: 'During automated AST similarity grading for Algorithms Lab 4, an anomalous 94% code structure overlap was flagged between two benchmark submissions.',
      reportingPerson: 'Dr. Meera Sharma (HoD - CSE)',
      reportingDepartment: 'Computer Science & Engineering',
      personsInvolved: [
        {
          id: 'p-1',
          name: 'Rahul Verma',
          identifier: 'Student Ref #CS-8902',
          role: 'RESPONDENT',
          department: 'Computer Science & Engineering',
          notes: 'Primary benchmark author flagged on similarity AST report.',
        },
        {
          id: 'p-2',
          name: 'Kavita Iyer',
          identifier: 'Student Ref #CS-8915',
          role: 'INVOLVED',
          department: 'Computer Science & Engineering',
          notes: 'Secondary repository branch sharing identical test suite structure.',
        },
      ],
      witnesses: [
        {
          id: 'w-1',
          name: 'Vikram Joshi',
          designation: 'Senior Lab Teaching Assistant (Turing Lab 3B)',
          statementSummary: 'Logged parallel git commit hashes with 2-minute delta during unsupervised evening hours.',
          contactRef: 'v.joshi@institution.edu',
        },
        {
          id: 'w-2',
          name: 'Pooja Nair',
          designation: 'Undergraduate Peer Proctor',
          statementSummary: 'Confirmed both workstations were occupied simultaneously in pod 4.',
          contactRef: 'p.nair@institution.edu',
        },
      ],
      witnessCount: 2,
      createdAt: '2026-09-08T10:30:00Z',
      evidenceItems: [
        {
          id: 'ev-01',
          fileName: 'similarity_report_ast_diff.pdf',
          fileSize: 428000,
          mimeType: 'application/pdf',
          sha256Checksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          storageKey: 'cases/EDU-2026-00042/evidence/ast_diff.pdf',
          uploadedBy: 'Dr. Meera Sharma',
          uploadedAt: '2026-09-08T10:35:00Z',
        },
        {
          id: 'ev-02',
          fileName: 'git_commit_timings_log.csv',
          fileSize: 18400,
          mimeType: 'text/csv',
          sha256Checksum: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
          storageKey: 'cases/EDU-2026-00042/evidence/git_timings.csv',
          uploadedBy: 'Dr. Meera Sharma',
          uploadedAt: '2026-09-08T10:36:00Z',
        },
      ],
    },
    // Exact 8-step Due-Process Statutory Checklist (Step 3)
    checklistItems: [
      {
        id: 'chk-1',
        caseId: 'case-2026-00042',
        stepNumber: 1,
        requirement: 'Student notified?',
        description: 'Formal policy-compliant Show-Cause Notice prepared and dispatched to official student address.',
        dueDate: '2026-09-10T18:00:00Z',
        completedAt: '2026-09-10T09:30:00Z',
        completedBy: 'Sarah Jenkins, Esq. (Admin)',
        status: 'COMPLETED',
        evidenceRef: 'not-001',
        notes: 'Notice of charge dispatched citing Section 4.2(B).',
      },
      {
        id: 'chk-2',
        caseId: 'case-2026-00042',
        stepNumber: 2,
        requirement: 'Notice delivered?',
        description: 'Electronic delivery confirmed and logged via institutional server proof.',
        dueDate: '2026-09-11T18:00:00Z',
        completedAt: '2026-09-10T11:42:00Z',
        completedBy: 'System Auto-Audit',
        status: 'COMPLETED',
        notes: 'Delivered to official.student.cs8902@institution.edu with server verification receipt.',
      },
      {
        id: 'chk-3',
        caseId: 'case-2026-00042',
        stepNumber: 3,
        requirement: 'Response window provided?',
        description: 'Mandatory 7-day statutory representation window currently open.',
        dueDate: '2026-09-17T18:00:00Z',
        status: 'IN_PROGRESS',
        notes: 'Window expires 17-Sep-2026 at 18:00 UTC.',
      },
      {
        id: 'chk-4',
        caseId: 'case-2026-00042',
        stepNumber: 4,
        requirement: 'Student given right to be heard?',
        description: 'Opportunity to inspect AST evidence and nominate student peer advocate.',
        dueDate: '2026-09-19T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-5',
        caseId: 'case-2026-00042',
        stepNumber: 5,
        requirement: 'Committee correctly constituted?',
        description: 'Verification of minimum 3 non-recused panel members and conflict disclosures.',
        dueDate: '2026-09-20T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-6',
        caseId: 'case-2026-00042',
        stepNumber: 6,
        requirement: 'Required documents submitted?',
        description: 'Evidence diffs, git commit ledger, witness statements, and student written response deposited.',
        dueDate: '2026-09-22T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-7',
        caseId: 'case-2026-00042',
        stepNumber: 7,
        requirement: 'Hearing completed?',
        description: 'Convening oral inquiry with attendance records and contemporaneous minutes.',
        dueDate: '2026-09-25T18:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-8',
        caseId: 'case-2026-00042',
        stepNumber: 8,
        requirement: 'Decision recorded?',
        description: 'Authorized human authority records finding of responsibility, sanction, and appeal route.',
        dueDate: '2026-09-28T18:00:00Z',
        status: 'PENDING',
      },
    ],
    notices: [
      {
        id: 'not-001',
        caseId: 'case-2026-00042',
        caseNumber: 'EDU-2026-00042',
        type: 'SHOW_CAUSE_NOTICE',
        recipientRef: 'official.student.cs8902@institution.edu',
        subject: 'FORMAL SHOW-CAUSE NOTICE — Ref: EDU-2026-00042',
        contentMarkdown: `### OFFICE OF THE REGISTRAR & DISCIPLINARY TRIBUNAL
**DATE:** 10 September 2026  
**CASE FILE:** EDU-2026-00042  
**RESPONDENT:** Student Record Reference #CS-8902 (Rahul Verma)  

**STATEMENT OF ALLEGATION:**
You are formally notified of an inquiry under Academic Integrity Code Section 4.2(B) regarding anomalous code duplication in Assignment 4 (Algorithms Lab).

**STATUTORY RIGHTS & PROCEDURES:**
1. You have the right to submit a written reply within **7 calendar days** (Deadline: 17 September 2026, 18:00).
2. You have the right to inspect all evidence items deposited in the cryptographic locker.
3. You have the right to be accompanied by an accredited student advocate during oral inquiry.
4. Presumption of innocence remains in force until deliberate committee finding.`,
        generatedDocHash: '3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855a',
        deliveryStatus: 'DELIVERED',
        deliveryProof: 'SES-REC-20260910-9948271 (Electronic Server Dispatch Confirmed)',
        acknowledgementStatus: 'ACKNOWLEDGED',
        acknowledgedAt: '2026-09-10T11:42:00Z',
        acknowledgementNote: 'Recipient authenticated through Student Portal and verified receipt of Show-Cause notice.',
        responseDeadline: '2026-09-17T18:00:00Z',
        sentAt: '2026-09-10T09:30:00Z',
        createdAt: '2026-09-10T09:15:00Z',
      },
    ],
    committeeRecord: {
      id: 'com-00042',
      caseId: 'case-2026-00042',
      committeeChair: 'Dr. Rajiv Menon',
      membersAssigned: ['Dr. Rajiv Menon', 'Prof. Arthur Sterling', 'Dr. Elena Rostova'],
      quorumRequired: 3,
      quorumPresent: 3,
      isQuorumMet: true,
      studentAttended: false,
      updatedAt: '2026-09-10T14:15:00Z',
    },
    sanctionTracking: {
      requirements: [
        'Remedial Academic Integrity Seminar (8 Hours)',
        'Independent laboratory benchmark re-submission under proctored supervision',
      ],
      completionStatus: 'PENDING',
      deadline: '2026-10-30T18:00:00Z',
      appealStatus: 'NO_APPEAL',
      retentionExpiryDate: '2029-09-08T10:30:00Z',
    },
  },
  {
    id: 'case-2026-00038',
    caseNumber: 'EDU-2026-00038',
    title: 'Disorderly Conduct & Sound System Breach in Central Quadrangle',
    status: 'DECISION_RECORDED',
    department: 'Office of Student Affairs',
    studentRegNoHash: '4a1b2c3d4e5f67890123456789abcdef01234567',
    studentDisplayRef: 'Student Ref #ME-4410',
    competentAuthorityId: 'user-dean-students',
    offenceCategoryId: 'cat-cond-01',
    offenceCategory: OFFENCE_CATEGORIES[2],
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-02T16:00:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00038',
      caseId: 'case-2026-00038',
      incidentDate: '2026-08-24T21:30:00Z',
      location: 'Central Academic Quadrangle',
      description: 'Unauthorized high-decibel audio amplification utilized during quiet study hours preceding mid-semester evaluations.',
      reportingPerson: 'Capt. Sunil Saxena (Chief Security Marshal)',
      reportingDepartment: 'Campus Security & Marshals',
      personsInvolved: [
        {
          id: 'p-38-1',
          name: 'Devanand Patel',
          identifier: 'Student Ref #ME-4410',
          role: 'RESPONDENT',
          department: 'Mechanical Engineering',
        },
      ],
      witnesses: [
        {
          id: 'w-38-1',
          name: 'Gopal Krishnan',
          designation: 'Campus Security Officer on Duty',
          statementSummary: 'Student complied immediately when requested to dismantle audio amplification equipment.',
        },
      ],
      witnessCount: 1,
      createdAt: '2026-08-25T11:00:00Z',
      evidenceItems: [
        {
          id: 'ev-38-1',
          fileName: 'security_decibel_log_quad.pdf',
          fileSize: 112000,
          mimeType: 'application/pdf',
          sha256Checksum: '5c2e3a1b4f6d8e9c0b1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a',
          storageKey: 'cases/EDU-2026-00038/evidence/decibel_log.pdf',
          uploadedBy: 'Capt. Sunil Saxena',
          uploadedAt: '2026-08-25T11:05:00Z',
        },
      ],
    },
    checklistItems: [
      {
        id: 'chk-38-1',
        caseId: 'case-2026-00038',
        stepNumber: 1,
        requirement: 'Student notified?',
        description: 'Notice dispatched via official channel.',
        dueDate: '2026-08-26T18:00:00Z',
        completedAt: '2026-08-26T10:00:00Z',
        completedBy: 'Prof. Arthur Sterling',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-2',
        caseId: 'case-2026-00038',
        stepNumber: 2,
        requirement: 'Notice delivered?',
        description: 'Delivered to registered email.',
        dueDate: '2026-08-27T18:00:00Z',
        completedAt: '2026-08-26T10:15:00Z',
        completedBy: 'System Auto-Audit',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-3',
        caseId: 'case-2026-00038',
        stepNumber: 3,
        requirement: 'Response window provided?',
        description: '7-day statutory period concluded.',
        dueDate: '2026-09-01T18:00:00Z',
        completedAt: '2026-08-30T14:00:00Z',
        completedBy: 'Devanand Patel',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-4',
        caseId: 'case-2026-00038',
        stepNumber: 4,
        requirement: 'Student given right to be heard?',
        description: 'Right exercised; student council representative present.',
        dueDate: '2026-09-01T14:00:00Z',
        completedAt: '2026-09-01T14:30:00Z',
        completedBy: 'Prof. Arthur Sterling',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-5',
        caseId: 'case-2026-00038',
        stepNumber: 5,
        requirement: 'Committee correctly constituted?',
        description: 'Quorum of 3 verified without conflict.',
        dueDate: '2026-09-01T14:00:00Z',
        completedAt: '2026-09-01T14:00:00Z',
        completedBy: 'Prof. Arthur Sterling',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-6',
        caseId: 'case-2026-00038',
        stepNumber: 6,
        requirement: 'Required documents submitted?',
        description: 'Security logs and written apology submitted.',
        dueDate: '2026-09-01T14:00:00Z',
        completedAt: '2026-09-01T14:15:00Z',
        completedBy: 'Sarah Jenkins, Esq.',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-7',
        caseId: 'case-2026-00038',
        stepNumber: 7,
        requirement: 'Hearing completed?',
        description: 'Convened at Senate Chamber B with minutes taken.',
        dueDate: '2026-09-01T16:00:00Z',
        completedAt: '2026-09-01T16:30:00Z',
        completedBy: 'Disciplinary Committee',
        status: 'COMPLETED',
      },
      {
        id: 'chk-38-8',
        caseId: 'case-2026-00038',
        stepNumber: 8,
        requirement: 'Decision recorded?',
        description: 'Reasoned order and sanction recorded.',
        dueDate: '2026-09-02T16:00:00Z',
        completedAt: '2026-09-02T15:30:00Z',
        completedBy: 'Prof. Arthur Sterling',
        status: 'COMPLETED',
      },
    ],
    notices: [
      {
        id: 'not-038',
        caseId: 'case-2026-00038',
        caseNumber: 'EDU-2026-00038',
        type: 'SHOW_CAUSE_NOTICE',
        recipientRef: 'official.student.me4410@institution.edu',
        subject: 'FORMAL SHOW-CAUSE NOTICE — Ref: EDU-2026-00038',
        contentMarkdown: `### OFFICE OF STUDENT AFFAIRS\nFormal Show-Cause Notice citing Conduct Code Section 2.1.`,
        generatedDocHash: '8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a',
        deliveryStatus: 'DELIVERED',
        deliveryProof: 'SES-REC-20260826-102941',
        acknowledgementStatus: 'ACKNOWLEDGED',
        acknowledgedAt: '2026-08-26T12:00:00Z',
        responseDeadline: '2026-09-01T18:00:00Z',
        sentAt: '2026-08-26T10:00:00Z',
        createdAt: '2026-08-26T09:45:00Z',
      },
    ],
    committeeRecord: {
      id: 'com-00038',
      caseId: 'case-2026-00038',
      committeeChair: 'Prof. Arthur Sterling',
      membersAssigned: ['Prof. Arthur Sterling', 'Dr. Meera Sharma', 'Dr. David Vance'],
      hearingDate: '2026-09-01T14:00:00Z',
      hearingVenue: 'Senate Chamber B',
      quorumRequired: 3,
      quorumPresent: 3,
      isQuorumMet: true,
      studentAttended: true,
      studentRepresentative: 'Student Council Ombudsman',
      deliberationMinutes: 'Student demonstrated remorse and explained amplification was unauthorized addition by third party. Quorum confirmed unanimous finding of minor responsibility.',
      updatedAt: '2026-09-01T16:30:00Z',
    },
    decision: {
      id: 'dec-00038',
      caseId: 'case-2026-00038',
      decidedBy: 'Prof. Arthur Sterling (Dean of Student Affairs)',
      decidingAuthority: 'Office of the Dean of Student Affairs',
      verdict: 'Charge Substantiated (Minor Infraction)',
      reasoningText: 'Having evaluated the testimony and witness logs, the committee determined that while sound decibel limits were exceeded, the student took prompt corrective action when requested by campus security. A proportional educational remedy is appropriate.',
      sanctionImposed: 'Written Admonition + 10 Hours Campus Library Service restitution',
      sanctionStartDate: '2026-09-05T00:00:00Z',
      sanctionEndDate: '2026-09-30T00:00:00Z',
      appealRoute: 'Executive Disciplinary Appeals Tribunal',
      appealDeadline: '2026-09-16T18:00:00Z',
      appealSubmitted: false,
      decidedAt: '2026-09-02T15:30:00Z',
      decisionDocHash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    },
    sanctionTracking: {
      requirements: [
        'Submission of formal Written Admonition acknowledgment',
        '10 Hours supervised Campus Library Service restitution',
      ],
      completionStatus: 'IN_PROGRESS',
      deadline: '2026-09-30T00:00:00Z',
      appealStatus: 'NO_APPEAL',
      closedAt: '2026-09-02T16:00:00Z',
      retentionExpiryDate: '2028-09-02T16:00:00Z',
    },
  },
  {
    id: 'case-2026-00045',
    caseNumber: 'EDU-2026-00045',
    title: 'Possession of Unauthorized Computational Aid in Proctored Midterm',
    status: 'HEARING_SCHEDULED',
    department: 'Electrical Engineering & Ethics Council',
    studentRegNoHash: '5e8b3c2d1a4f67890123456789abcdef01239999',
    studentDisplayRef: 'Student Ref #EE-2914',
    competentAuthorityId: 'user-committee-chair',
    offenceCategoryId: 'cat-acad-02',
    offenceCategory: OFFENCE_CATEGORIES[1],
    createdAt: '2026-09-09T09:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00045',
      caseId: 'case-2026-00045',
      incidentDate: '2026-09-08T15:00:00Z',
      location: 'Maxwell Hall 101 (Examination Center)',
      description: 'Invigilator intercepted an unauthorized programmable smartwatch communicating during Signals & Systems midterm.',
      reportingPerson: 'Dr. Rajiv Menon (Proctorial Board)',
      reportingDepartment: 'Electrical Engineering',
      personsInvolved: [
        {
          id: 'p-45-1',
          name: 'Siddharth Rao',
          identifier: 'Student Ref #EE-2914',
          role: 'RESPONDENT',
          department: 'Electrical Engineering',
        },
      ],
      witnesses: [
        {
          id: 'w-45-1',
          name: 'Prof. Anita Desai',
          designation: 'Chief Examination Invigilator',
          statementSummary: 'Observed repeated device screen activation during section B calculation questions.',
        },
      ],
      witnessCount: 1,
      createdAt: '2026-09-09T09:00:00Z',
      evidenceItems: [
        {
          id: 'ev-45-1',
          fileName: 'device_confiscation_receipt.pdf',
          fileSize: 204000,
          mimeType: 'application/pdf',
          sha256Checksum: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
          storageKey: 'cases/EDU-2026-00045/evidence/confiscation_receipt.pdf',
          uploadedBy: 'Dr. Rajiv Menon',
          uploadedAt: '2026-09-09T09:15:00Z',
        },
      ],
    },
    checklistItems: [
      {
        id: 'chk-45-1',
        caseId: 'case-2026-00045',
        stepNumber: 1,
        requirement: 'Student notified?',
        description: 'Notice of charge dispatched.',
        dueDate: '2026-09-10T18:00:00Z',
        completedAt: '2026-09-10T10:00:00Z',
        completedBy: 'Sarah Jenkins, Esq.',
        status: 'COMPLETED',
      },
      {
        id: 'chk-45-2',
        caseId: 'case-2026-00045',
        stepNumber: 2,
        requirement: 'Notice delivered?',
        description: 'Delivery confirmed to student portal.',
        dueDate: '2026-09-11T18:00:00Z',
        completedAt: '2026-09-10T10:30:00Z',
        completedBy: 'System Auto-Audit',
        status: 'COMPLETED',
      },
      {
        id: 'chk-45-3',
        caseId: 'case-2026-00045',
        stepNumber: 3,
        requirement: 'Response window provided?',
        description: '5-day representation window concluded.',
        dueDate: '2026-09-15T18:00:00Z',
        completedAt: '2026-09-12T09:00:00Z',
        completedBy: 'Siddharth Rao',
        status: 'COMPLETED',
      },
      {
        id: 'chk-45-4',
        caseId: 'case-2026-00045',
        stepNumber: 4,
        requirement: 'Student given right to be heard?',
        description: 'Hearing scheduled at Senate Chamber.',
        dueDate: '2026-09-16T14:00:00Z',
        status: 'IN_PROGRESS',
      },
      {
        id: 'chk-45-5',
        caseId: 'case-2026-00045',
        stepNumber: 5,
        requirement: 'Committee correctly constituted?',
        description: 'Quorum of 4 required under Examination Statute XII. Currently 3 assigned, 1 pending confirmation.',
        dueDate: '2026-09-16T12:00:00Z',
        status: 'IN_PROGRESS',
      },
      {
        id: 'chk-45-6',
        caseId: 'case-2026-00045',
        stepNumber: 6,
        requirement: 'Required documents submitted?',
        description: 'Device logs submitted.',
        dueDate: '2026-09-16T12:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-45-7',
        caseId: 'case-2026-00045',
        stepNumber: 7,
        requirement: 'Hearing completed?',
        description: 'Scheduled for 16-Sep-2026.',
        dueDate: '2026-09-16T16:00:00Z',
        status: 'PENDING',
      },
      {
        id: 'chk-45-8',
        caseId: 'case-2026-00045',
        stepNumber: 8,
        requirement: 'Decision recorded?',
        description: 'Human decision order pending.',
        dueDate: '2026-09-18T18:00:00Z',
        status: 'PENDING',
      },
    ],
    notices: [],
    committeeRecord: {
      id: 'com-00045',
      caseId: 'case-2026-00045',
      committeeChair: 'Dr. Rajiv Menon',
      membersAssigned: ['Dr. Rajiv Menon', 'Prof. Arthur Sterling', 'Dr. David Vance'],
      hearingDate: '2026-09-16T14:00:00Z',
      hearingVenue: 'Senate Chamber A',
      quorumRequired: 4,
      quorumPresent: 3,
      isQuorumMet: false,
      studentAttended: false,
      updatedAt: '2026-09-12T11:00:00Z',
    },
  },
  // CLOSED STUDENT CASES ARCHIVE (Stored Historical Records)
  {
    id: 'case-2025-00118',
    caseNumber: 'EDU-2025-00118',
    title: 'Uncited Reference Duplication in Operating Systems Lab Submission',
    status: 'CLOSED',
    department: 'Computer Science & Engineering',
    studentRegNoHash: '7c9e2b8a4f1a23847b2c91823746a5b6c7d8e9f0',
    studentDisplayRef: 'Student Ref #CS-8902',
    competentAuthorityId: 'user-hod-cse',
    offenceCategoryId: 'cat-acad-01',
    offenceCategory: OFFENCE_CATEGORIES[0],
    createdAt: '2025-10-10T10:00:00Z',
    updatedAt: '2025-11-14T16:00:00Z',
    closedAt: '2025-11-14T16:00:00Z',
    retentionExpiryAt: '2028-11-14T16:00:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00118',
      caseId: 'case-2025-00118',
      incidentDate: '2025-10-08T14:00:00Z',
      location: 'Software Systems Laboratory 2A',
      description: 'First-year lab submission contained code blocks adapted from online open repository without standard academic bibliographic reference.',
      reportingPerson: 'Dr. Meera Sharma (HoD - CSE)',
      reportingDepartment: 'Computer Science & Engineering',
      personsInvolved: [
        {
          id: 'p-118-1',
          name: 'Rahul Verma',
          identifier: 'Student Ref #CS-8902',
          role: 'RESPONDENT',
          department: 'Computer Science & Engineering',
        },
      ],
      witnesses: [],
      witnessCount: 0,
      createdAt: '2025-10-10T10:00:00Z',
      evidenceItems: [
        {
          id: 'ev-118-1',
          fileName: 'citation_similarity_audit_v1.pdf',
          fileSize: 185000,
          mimeType: 'application/pdf',
          sha256Checksum: '9f8e7d6c5b4a39281726354456789abcdef0123456789abcdef0123456789abc',
          storageKey: 'cases/EDU-2025-00118/evidence/citation_similarity.pdf',
          uploadedBy: 'Dr. Meera Sharma',
          uploadedAt: '2025-10-10T10:15:00Z',
        },
      ],
    },
    checklistItems: [
      { id: 'chk-118-1', caseId: 'case-2025-00118', stepNumber: 1, requirement: 'Student notified?', description: 'Written notice delivered via portal.', dueDate: '2025-10-12T10:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-2', caseId: 'case-2025-00118', stepNumber: 2, requirement: 'Notice delivered?', description: 'Delivery acknowledged by respondent.', dueDate: '2025-10-12T12:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-3', caseId: 'case-2025-00118', stepNumber: 3, requirement: 'Response window provided?', description: '7-day response window observed.', dueDate: '2025-10-19T17:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-4', caseId: 'case-2025-00118', stepNumber: 4, requirement: 'Student given right to be heard?', description: 'Departmental hearing opportunity granted.', dueDate: '2025-10-21T14:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-5', caseId: 'case-2025-00118', stepNumber: 5, requirement: 'Committee correctly constituted?', description: 'Departmental Ethics Committee verified.', dueDate: '2025-10-21T14:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-6', caseId: 'case-2025-00118', stepNumber: 6, requirement: 'Required documents submitted?', description: 'Turnitin report and syllabus submitted.', dueDate: '2025-10-21T14:30:00Z', status: 'COMPLETED' },
      { id: 'chk-118-7', caseId: 'case-2025-00118', stepNumber: 7, requirement: 'Hearing completed?', description: 'Oral statement recorded.', dueDate: '2025-10-21T16:00:00Z', status: 'COMPLETED' },
      { id: 'chk-118-8', caseId: 'case-2025-00118', stepNumber: 8, requirement: 'Decision recorded?', description: 'Educational remediation order signed.', dueDate: '2025-10-22T14:00:00Z', status: 'COMPLETED' },
    ],
    notices: [],
    decision: {
      id: 'dec-00118',
      caseId: 'case-2025-00118',
      decidedBy: 'Dr. Meera Sharma (HoD - CSE)',
      decidingAuthority: 'Department of Computer Science & Engineering',
      verdict: 'Substantiated (First-Time Negligent Infraction — Educational Remediation)',
      reasoningText: 'Student demonstrated genuine misunderstanding of source attribution guidelines during oral explanation. Cooperative attitude and lack of premeditation supported restorative rather than punitive measures.',
      sanctionImposed: 'Mandatory 8-Hour Academic Citation & Code Ethics Workshop + Lab Assignment Resubmission',
      sanctionStartDate: '2025-10-25T00:00:00Z',
      sanctionEndDate: '2025-11-10T00:00:00Z',
      appealRoute: 'Faculty Ethics Board',
      appealDeadline: '2025-11-05T18:00:00Z',
      appealSubmitted: false,
      decidedAt: '2025-10-22T14:00:00Z',
      decisionDocHash: 'sha256-dec-2025-00118-verified-compliance-order',
    },
    sanctionTracking: {
      requirements: [
        '8-Hour Academic Citation & Code Ethics Seminar Attendance',
        'Independent proctored laboratory code resubmission',
      ],
      completionStatus: 'COMPLETED',
      deadline: '2025-11-10T00:00:00Z',
      appealStatus: 'NO_APPEAL',
      closedAt: '2025-11-14T16:00:00Z',
      retentionExpiryDate: '2028-11-14T16:00:00Z',
    },
  },
  {
    id: 'case-2025-00092',
    caseNumber: 'EDU-2025-00092',
    title: 'Circuit Fabrication Laboratory Apparatus Accidental Overload',
    status: 'CLOSED',
    department: 'Electrical Engineering & Ethics Council',
    studentRegNoHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    studentDisplayRef: 'Student Ref #EC-2094',
    competentAuthorityId: 'user-committee-chair',
    offenceCategoryId: 'cat-cond-02',
    offenceCategory: OFFENCE_CATEGORIES[3],
    createdAt: '2025-09-15T11:00:00Z',
    updatedAt: '2025-10-20T17:00:00Z',
    closedAt: '2025-10-20T17:00:00Z',
    retentionExpiryAt: '2028-10-20T17:00:00Z',
    isPurged: false,
    incidentReport: {
      id: 'inc-00092',
      caseId: 'case-2025-00092',
      incidentDate: '2025-09-14T16:30:00Z',
      location: 'Microelectronics Fabrication Bay 1',
      description: 'Power surge trip caused by improper resistor bridge configuration during unauthorized solo experiment hour.',
      reportingPerson: 'Dr. Rajiv Menon',
      reportingDepartment: 'Electrical Engineering',
      personsInvolved: [
        {
          id: 'p-92-1',
          name: 'Priya Sundaram',
          identifier: 'Student Ref #EC-2094',
          role: 'RESPONDENT',
          department: 'Electronics & Communication',
        },
      ],
      witnesses: [],
      witnessCount: 0,
      createdAt: '2025-09-15T11:00:00Z',
      evidenceItems: [],
    },
    checklistItems: [
      { id: 'chk-92-1', caseId: 'case-2025-00092', stepNumber: 1, requirement: 'Student notified?', description: 'Safety officer delivered incident note.', dueDate: '2025-09-16T10:00:00Z', status: 'COMPLETED' },
      { id: 'chk-92-8', caseId: 'case-2025-00092', stepNumber: 8, requirement: 'Decision recorded?', description: 'Voluntary disclosure resolution order recorded.', dueDate: '2025-09-25T14:00:00Z', status: 'COMPLETED' },
    ],
    notices: [],
    decision: {
      id: 'dec-00092',
      caseId: 'case-2025-00092',
      decidedBy: 'Dr. Rajiv Menon (Ethics Council)',
      decidingAuthority: 'Campus Safety & Property Oversight',
      verdict: 'Accidental Misuse with Voluntary Disclosure',
      reasoningText: 'Student immediately notified laboratory technician of apparatus trip and assisted in fuse inspection. No willful damage was substantiated.',
      sanctionImposed: 'Laboratory High-Voltage Safety Re-Certification Seminar (Satisfied)',
      sanctionStartDate: '2025-09-25T00:00:00Z',
      sanctionEndDate: '2025-10-15T00:00:00Z',
      appealRoute: 'Campus Facilities Tribunal',
      appealDeadline: '2025-10-05T18:00:00Z',
      appealSubmitted: false,
      decidedAt: '2025-09-22T11:00:00Z',
      decisionDocHash: 'sha256-dec-2025-00092-restitution-satisfied',
    },
    sanctionTracking: {
      requirements: ['Laboratory High-Voltage Safety Re-Certification (4 Hours)'],
      completionStatus: 'COMPLETED',
      deadline: '2025-10-15T00:00:00Z',
      appealStatus: 'NO_APPEAL',
      closedAt: '2025-10-20T17:00:00Z',
      retentionExpiryDate: '2028-10-20T17:00:00Z',
    },
  },
];
